name: Build and Publish Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  push-to-registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: 获取 Git 文件
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: 安装依赖并编译
        run: |
          npm i -g pnpm
          pnpm i
          pnpm run build

      - name: 获取 Tag
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - name: 登录到 DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: 构建和推送
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            lifeni/qing-dev:${{ steps.vars.outputs.tag }}
            lifeni/qing-dev:latest
